development:
  adapter: postgresql
  database: angular_workshop_backend_development
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: angular_workshop_backend_test
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432
